// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"access-management/models"
)

// Injectors from wire.go:

func InitApp() (*models.DB, error) {
	config, err := models.NewConfig()
	if err != nil {
		return nil, err
	}
	db := models.NewDB(config)
	return db, nil
}
