// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

//go:generate wire
package main

import (
	"access-management/pkg/config"
	"access-management/pkg/domain/db/psql"
	"access-management/pkg/domain/user"
	"access-management/pkg/domain/user/delivery/http"
	"access-management/pkg/domain/user/repository"
	"access-management/pkg/domain/user/service"
	"access-management/pkg/server"
)

// Injectors from wire.go:

func InitApp() (*server.Server, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, err
	}
	db := psql.NewDB(configConfig)
	userRepository := repository.User(db)
	userService := service.User(userRepository)
	delivery := http.User(userService)
	v := user.HttpUserRouters(delivery)
	serverServer := server.NewServer(configConfig, v)
	return serverServer, nil
}
